Ammunition calibers PR and the crash that cause a pain in my ass
Vault-Overseers/nuclear-14 pull request #100
Opened 2023-08-21 23:05 UTC by PatoGrone

Ammunition calibers PR:
added 11 different calibers with 12 magazines and 11 ammo boxes for all of them.
added 2 guns, the riot shotgun, just a combat shotgun chambered on 20 gauge, and the pipe rifle, chambered in .308. in a future PR i will add the ammo variants (AP, HP, FMJ, etc).
i gotta inform that i have a problem at the moment of insert any cartride or magazine inside of a gun, causing to crash my tests plays. i cant really see what is causing that and i need extra eyes has always
![Captura](https://github.com/Vault-Overseers/nuclear-14/assets/134236674/b8df60f8-314a-4076-a909-e7bc3b040cfe)

2023-08-22 11:55 UTC, Peptide90 requested changes
Quick scan, found two things, the latter is probably your crash. 

You need to create tag prototypes for any new tags added. These are probably in resources/prototypes/Nuclear14/tags.yml

2023-08-22 11:55 UTC, Peptide90 commented on Resources/Prototypes/Nuclear14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/50.yml
What da file doin

2023-08-22 11:55 UTC, Peptide90 commented on Resources/Prototypes/Nuclear14/Entities/Objects/Weapons/Guns/Ammunition/Magazines/10mm.yml
> +        - N14CartridgePistol10
Need to make sure there’s a tag entry for this.

2023-08-22 17:37 UTC, Peptide90 requested changes

2023-08-22 17:37 UTC, Peptide90 commented on Resources/Prototypes/Nuclear14/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +    sprite: Nuclear14/Objects/Weapons/Guns/Rifles/servicerifle.rsi
Sprite isn’t in this PR

2023-08-22 17:37 UTC, Peptide90 commented on Resources/Prototypes/Nuclear14/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +    sprite: Nuclear14/Objects/Weapons/Guns/Rifles/servicerifle.rsi
Same here

2023-08-28 00:53 UTC, Cheackraze approved these changes

2023-08-28 01:05 UTC, merged