Removed useless ss14 decals to make mapping easier and added my full …
Vault-Overseers/nuclear-14 pull request #478
Opened 2024-08-25 15:59 UTC by FizCap

Removed useless ss14 decals to make mapping easier and added my full white decal

2024-08-26 12:37 UTC, Peptide90 requested changes

2024-08-26 12:37 UTC, Peptide90 commented on Resources/Textures/_Nuclear14/Decals/FullWhite.rsi/meta.json
> +  "license": null,
Not sure if null is supported or not. You can do CC-0 if you don't care about licensing or CC-BY-SA-3.0 if you want to be credited for it properly and it to be share able.

2024-08-27 01:10 UTC, justzick commented
Null is supported.

2024-08-27 19:06 UTC, FizCap commented
Fix Psycho Boss Spawner, Add TImed Psycho Spawners as well now

2024-08-30 20:27 UTC, Peptide90 approved these changes

2024-08-30 20:27 UTC, merged