Injectable Chem Basics
Vault-Overseers/nuclear-14 pull request #6
Opened 2022-07-11 12:07 UTC by Ablankmann

## About the PR 
This PR moves the Nuka Cola reagent to a Nuclear14 file to avoid mixups, and adds basic reagents + injectors for all injectable chems, which are as follows:

Stimpak
Super Stimpak
Med-X 
Psycho 
Jet
Turbo

Note than the injectors use medipen sprites, and need to be replaced with actual fallout sprites ASAP.
When this is merged, i'll get to work on the pill-based chems

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

2022-07-11 12:11 UTC, Ablankmann commented
This is finished for the most part, all that's left now are Sprites and stuff for Med-X and Psycho

2022-08-14 03:44 UTC, Veritius requested changes

2022-08-14 03:44 UTC, Veritius commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +=======
This definitely isn't meant to be here. This is a line inserted by git conflicts, and is causing the yaml parser to reject it.

2022-10-24 01:04 UTC, Partmedia commented
Hi @Ablankmann, are you still available to make the suggestions from review of your PR?

2022-10-31 22:24 UTC, closed without merging